version: "3.8"
services:
  rustapiempleado:
    container_name: rustapiempleado
    image: h2k2/rustapiempleado:${BUILD_NUMBER}
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL= mysql://userinfo:admin@mysql:3306/clientcodedb
    ports:
      - '9001:9001'
    networks:
      - my-network-mysql
networks:
  my-network-mysql:
    external: true